# Generated by Django 4.2.11 on 2025-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='mute_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
