# Generated by Django 5.1.4 on 2025-01-24 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=127, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
