# Generated by Django 5.1.4 on 2024-12-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_status_label_invitation'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='rooms', to='user.user'),
        ),
    ]
