# Generated by Django 5.1.4 on 2025-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_userstatus_mute_end_time'),
        ('room', '0003_message_is_deleted_message_updated_at'),
    ]

    operations = [
    ]
