# Generated by Django 5.1.4 on 2025-01-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('administrator', 'Administrateur'), ('user', 'Utilisateur'), ('muted', 'Muet'), ('banned', 'Banni')], default='user', max_length=127, unique=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
