# Generated by Django 5.1.4 on 2025-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_userstatus_status_delete_status'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstatus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('administrator', 'Administrateur'), ('user', 'Utilisateur'), ('muted', 'Muet'), ('banned', 'Banni')], default='user', max_length=127),
        ),
        migrations.AlterUniqueTogether(
            name='userstatus',
            unique_together={('user', 'room', 'status')},
        ),
    ]
